#create ec2 with install jdk,awscli,maven, ansible

AWSTemplateFormatVersion: 2010-09-09
Description: EC2 1
Resources:
  DuiHua:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: manar-ubuntu
      ImageId: ami-02f3416038bdb17fb

      InstanceType: t2.medium
      Tags: 
        - 
          Key: Name
          Value: DuiHua
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install openjdk-11-jre-headless -y
          sudo apt update
          sudo apt install maven -y
          sudo apt update
          sudo apt install awscli -y
          sudo apt update
          sudo apt install ansible -y
      SecurityGroupIds:
        - Ref: SecurityGroup


#create security group
  SecurityGroup: 
   Type: "AWS::EC2::SecurityGroup"
   Properties: 
      GroupDescription: "Allow http to client host"
      SecurityGroupIngress: 
        - 
          CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
        -
          CidrIp: 0.0.0.0/0
          FromPort: 8080
          IpProtocol: tcp
          ToPort: 8080
        -
          CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22